<?php
/**
 * Unit tests for the FAQ Accordion render.php wrapper attributes.
 *
 * Feature: block-theme-support
 * Validates: Requirements 7.1, 7.4, 7.5
 *
 * Tests that the render callback uses get_block_wrapper_attributes() correctly:
 * - Rendered output includes wrapper attributes from get_block_wrapper_attributes()
 * - Custom classes (icon position, animation) are present in the wrapper
 * - Supports-generated styles are included when block attributes contain style values
 * - Block renders correctly with empty/default attributes (backward compatibility)
 */

declare(strict_types=1);

namespace WPBits\AiFaqGenerator\Tests\Unit;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

use function WPBits\AiFaqGenerator\Blocks\FaqAccordion\render_faq_accordion_block;

class RenderWrapperAttributesTest extends TestCase
{
    /**
     * Valid FAQ items for testing wrapper attributes.
     */
    private array $validItems;

    protected function setUp(): void
    {
        parent::setUp();

        $this->validItems = [
            ['question' => 'What is WordPress?', 'answer' => 'A content management system.'],
            ['question' => 'Is it free?', 'answer' => 'Yes, WordPress is free and open source.'],
        ];

        // Reset supports-generated styles global.
        global $afg_test_block_wrapper_styles;
        $afg_test_block_wrapper_styles = '';
    }

    protected function tearDown(): void
    {
        global $afg_test_block_wrapper_styles;
        $afg_test_block_wrapper_styles = '';

        parent::tearDown();
    }

    // ─── Wrapper attributes from get_block_wrapper_attributes() ──────────────

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The rendered output must include the base WordPress block class
     * from get_block_wrapper_attributes().
     */
    #[Test]
    public function rendered_output_includes_base_block_class_from_wrapper_attributes(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        $this->assertStringContainsString('wp-block-wpbits-faq-accordion', $result);
    }

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The rendered wrapper div must use the attribute string format produced by
     * get_block_wrapper_attributes() (class="..." pattern).
     */
    #[Test]
    public function rendered_wrapper_uses_get_block_wrapper_attributes_format(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        // The wrapper div must contain the class attribute as generated by
        // get_block_wrapper_attributes() (e.g., <div class="wp-block-wpbits-faq-accordion ...">)
        $this->assertMatchesRegularExpression(
            '/<div\s+class="wp-block-wpbits-faq-accordion[^"]*"/',
            $result
        );
    }

    // ─── Custom classes (icon position) ─────────────────────────────────────

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The default icon position class (has-icon-left) should be present
     * in the wrapper when no iconPosition attribute is set.
     */
    #[Test]
    public function wrapper_includes_default_icon_position_class(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        $this->assertStringContainsString('has-icon-left', $result);
    }

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The has-icon-right class should appear when iconPosition is 'right'.
     */
    #[Test]
    public function wrapper_includes_icon_right_class_when_set(): void
    {
        $result = render_faq_accordion_block([
            'items'        => $this->validItems,
            'iconPosition' => 'right',
        ]);

        $this->assertStringContainsString('has-icon-right', $result);
    }

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The has-no-icon class should appear when iconPosition is 'none'.
     */
    #[Test]
    public function wrapper_includes_no_icon_class_when_position_is_none(): void
    {
        $result = render_faq_accordion_block([
            'items'        => $this->validItems,
            'iconPosition' => 'none',
        ]);

        $this->assertStringContainsString('has-no-icon', $result);
    }

    // ─── Custom classes (animation) ─────────────────────────────────────────

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The has-animation class should be present when enableAnimation is true.
     */
    #[Test]
    public function wrapper_includes_animation_class_when_enabled(): void
    {
        $result = render_faq_accordion_block([
            'items'           => $this->validItems,
            'enableAnimation' => true,
        ]);

        $this->assertStringContainsString('has-animation', $result);
    }

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * The has-animation class should NOT be present when enableAnimation is false.
     */
    #[Test]
    public function wrapper_excludes_animation_class_when_disabled(): void
    {
        $result = render_faq_accordion_block([
            'items'           => $this->validItems,
            'enableAnimation' => false,
        ]);

        $this->assertStringNotContainsString('has-animation', $result);
    }

    /**
     * **Validates: Requirements 7.1, 7.4**
     *
     * Both icon position and animation classes should coexist in the wrapper.
     */
    #[Test]
    public function wrapper_includes_both_icon_and_animation_classes(): void
    {
        $result = render_faq_accordion_block([
            'items'           => $this->validItems,
            'iconPosition'    => 'right',
            'enableAnimation' => true,
        ]);

        $this->assertStringContainsString('has-icon-right', $result);
        $this->assertStringContainsString('has-animation', $result);
    }

    // ─── Supports-generated styles ──────────────────────────────────────────

    /**
     * **Validates: Requirements 7.1**
     *
     * When WordPress generates inline styles from supports (simulated via
     * $afg_test_block_wrapper_styles), the rendered output should include
     * those styles in the wrapper element.
     */
    #[Test]
    public function wrapper_includes_supports_generated_inline_styles(): void
    {
        global $afg_test_block_wrapper_styles;
        $afg_test_block_wrapper_styles = 'color:#333;background-color:#fff;';

        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        $this->assertStringContainsString('style="', $result);
        $this->assertStringContainsString('color:#333', $result);
        $this->assertStringContainsString('background-color:#fff', $result);
    }

    /**
     * **Validates: Requirements 7.1**
     *
     * When supports-generated styles include spacing, they should appear
     * alongside the class attributes in the wrapper.
     */
    #[Test]
    public function wrapper_includes_supports_spacing_styles(): void
    {
        global $afg_test_block_wrapper_styles;
        $afg_test_block_wrapper_styles = 'padding-top:2em;padding-bottom:2em;';

        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        $this->assertStringContainsString('padding-top:2em', $result);
        $this->assertStringContainsString('padding-bottom:2em', $result);
    }

    /**
     * **Validates: Requirements 7.1**
     *
     * When supports-generated styles include border properties, they should
     * appear in the wrapper element.
     */
    #[Test]
    public function wrapper_includes_supports_border_styles(): void
    {
        global $afg_test_block_wrapper_styles;
        $afg_test_block_wrapper_styles = 'border-color:#ccc;border-width:2px;border-radius:8px;';

        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        $this->assertStringContainsString('border-color:#ccc', $result);
        $this->assertStringContainsString('border-width:2px', $result);
        $this->assertStringContainsString('border-radius:8px', $result);
    }

    // ─── Backward compatibility (default attributes) ────────────────────────

    /**
     * **Validates: Requirements 7.4, 7.5**
     *
     * When called with minimal/default attributes (only items), the block
     * should render correctly without errors, using default icon position.
     */
    #[Test]
    public function renders_correctly_with_only_items_attribute(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        // Should produce valid output with default classes.
        $this->assertNotEmpty($result);
        $this->assertStringContainsString('wp-block-wpbits-faq-accordion', $result);
        $this->assertStringContainsString('has-icon-left', $result);
        $this->assertStringNotContainsString('has-animation', $result);
    }

    /**
     * **Validates: Requirements 7.4, 7.5**
     *
     * The block output should contain FAQ content when rendered with
     * default attributes (pre-update block instances without new attributes).
     */
    #[Test]
    public function backward_compatible_rendering_contains_faq_content(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        // FAQ content should still be rendered correctly.
        $this->assertStringContainsString('What is WordPress?', $result);
        $this->assertStringContainsString('A content management system.', $result);
        $this->assertStringContainsString('<details', $result);
        $this->assertStringContainsString('<summary', $result);
    }

    /**
     * **Validates: Requirements 7.5**
     *
     * With no supports styles active and default attributes, the wrapper
     * should not include a style attribute (no unnecessary inline styles).
     */
    #[Test]
    public function no_inline_styles_when_no_supports_are_active(): void
    {
        $result = render_faq_accordion_block([
            'items' => $this->validItems,
        ]);

        // Extract the opening div tag.
        preg_match('/<div\s[^>]+>/', $result, $matches);
        $this->assertNotEmpty($matches);

        // The wrapper should not have a style attribute when no supports are set.
        $this->assertStringNotContainsString('style=', $matches[0]);
    }
}
